Q1------------------

CREATE TABLE CUSTOMER(
	ID INT(5) NOT NULL PRIMARY KEY,
	FirstName VARCHAR(15),
	LastName VARCHAR(15),
	City VARCHAR(20),
	Country CHAR(2),
	Phone VARCHAR(12)
);

CREATE TABLE ORDER_(
	ID INT(5) NOT NULL PRIMARY KEY,
	OrderDate DATE,
	OrderNumber INT(10),
	CustomerId INT(5),
	TotalAmount INT(10),
	CONSTRAINT FK_ORD FOREIGN KEY(CustomerId) REFERENCES CUSTOMER(ID)
);

-------------------
Q2-----------------

CREATE TABLE EMPLOYEE (
	EMP_ID INT(3) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(10),
	LAST_NAME VARCHAR(10),
	EMAIL VARCHAR(10),
	HIRE_DATE DATE,
	JOB_ID VARCHAR(10),
	SALARY INT(5),
	MANAGER_ID INT(3),
	DEPT_ID INT(3)
);

---------------------
Q3-------------------

CREATE TABLE PRODUCTS (
P_ID INT(4) NOT NULL PRIMARY KEY, 
P_NAME VARCHAR(20), 
UNITS INT(5), 
UNIT_PRICE INT(5), 
TYPE VARCHAR(20), 
S_ID INT(5),
INDEX(S_ID),
CONSTRAINT FK_PRODUCTS FOREIGN KEY(S_ID) REFERENCES SUPPLIERS(S_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SUPPLIERS(
S_ID INT(5) NOT NULL PRIMARY KEY,
S_NAME VARCHAR(50),
CONTACT VARCHAR(12),
CITY VARCHAR(15)
);

CREATE TABLE ORDERS(
ORDER_ID INT(4) NOT NULL PRIMARY KEY,
CUSTOMER_NAME VARCHAR(20),
ORDER_DATE DATE
);

CREATE TABLE ORDER_DETAIL(
P_ID INT(5),
ORDER_ID INT(4),
UNITS_PURCHASED INT(5),
INDEX(P_ID),
INDEX(ORDER_ID),
CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY(P_ID,ORDER_ID)
);